# Cloud Build configuration for automatic deployment
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/quran-assistant:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/quran-assistant:latest'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/quran-assistant:$COMMIT_SHA'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'quran-assistant'
      - '--image'
      - 'gcr.io/$PROJECT_ID/quran-assistant:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID,GOOGLE_GENAI_USE_VERTEXAI=true'
      - '--set-secrets'
      - 'TAVILY_API_KEY=TAVILY_API_KEY:latest'

images:
  - 'gcr.io/$PROJECT_ID/quran-assistant:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/quran-assistant:latest'

timeout: '1200s'
